CadastroDeLivros/CadastroDeLivros/Models/ErrorViewModel.cs
namespace CadastroDeLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroDeLivros/CadastroDeLivros/Models/Livro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CadastroDeLivros.Models
{
    public class Livro
    {
        [Key]
        public int LivroID { get; set; }
        [Required]
        [StringLength(255)]
        public string? Nome { get; set; }
        public string? Autores { get; set; }
        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        public string? AnoPublicacao { get; set; }
        public string? Idioma { get; set; }
        public int NumeroPaginas { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Valor { get; set; }
    }
}

CadastroDeLivros/CadastroDeLivros/Controllers/HomeController.cs
using CadastroDeLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadastroDeLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroDeLivros/CadastroDeLivros/Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CadastroDeLivros.Models;

namespace CadastroDeLivros.Controllers
{
    public class LivrosController : Controller
    {
        private readonly CadastroDeLivrosContext _context;

        public LivrosController(CadastroDeLivrosContext context)
        {
            _context = context;
        }

        // GET: Livros
        public IActionResult Index()
        {
            return View(_context.Livro.ToList());
        }

        // GET: Livros/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = _context.Livro
                .FirstOrDefault(m => m.LivroID == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // GET: Livros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Livros/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("LivroID,Nome,Autores,AnoPublicacao,Idioma,NumeroPaginas,Valor")] Livro livro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(livro);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livros/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = _context.Livro.Find(id);
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        // POST: Livros/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("LivroID,Nome,Autores,AnoPublicacao,Idioma,NumeroPaginas,Valor")] Livro livro)
        {
            if (id != livro.LivroID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.LivroID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        // GET: Livros/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = _context.Livro
                .FirstOrDefault(m => m.LivroID == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var livro = _context.Livro.Find(id);
            if (livro != null)
            {
                _context.Livro.Remove(livro);
            }

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(int id)
        {
            return _context.Livro.Any(e => e.LivroID == id);
        }
    }
}

CadastroDeLivros/CadastroDeLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CadastroDeLivros/CadastroDeLivros/Views/Livros/Create.cshtml
@model CadastroDeLivros.Models.Livro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autores" class="control-label"></label>
                <input asp-for="Autores" class="form-control" />
                <span asp-validation-for="Autores" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoPublicacao" class="control-label"></label>
                <input asp-for="AnoPublicacao" class="form-control" />
                <span asp-validation-for="AnoPublicacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idioma" class="control-label"></label>
                <input asp-for="Idioma" class="form-control" />
                <span asp-validation-for="Idioma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroPaginas" class="control-label"></label>
                <input asp-for="NumeroPaginas" class="form-control" />
                <span asp-validation-for="NumeroPaginas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroDeLivros/CadastroDeLivros/Views/Livros/Delete.cshtml
@model CadastroDeLivros.Models.Livro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Livro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autores)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoPublicacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoPublicacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idioma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idioma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPaginas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPaginas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LivroID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CadastroDeLivros/CadastroDeLivros/Views/Livros/Details.cshtml
@model CadastroDeLivros.Models.Livro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Livro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autores)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autores)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnoPublicacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnoPublicacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idioma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idioma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroPaginas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroPaginas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.LivroID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CadastroDeLivros/CadastroDeLivros/Views/Livros/Edit.cshtml
@model CadastroDeLivros.Models.Livro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LivroID" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autores" class="control-label"></label>
                <input asp-for="Autores" class="form-control" />
                <span asp-validation-for="Autores" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnoPublicacao" class="control-label"></label>
                <input asp-for="AnoPublicacao" class="form-control" />
                <span asp-validation-for="AnoPublicacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idioma" class="control-label"></label>
                <input asp-for="Idioma" class="form-control" />
                <span asp-validation-for="Idioma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroPaginas" class="control-label"></label>
                <input asp-for="NumeroPaginas" class="form-control" />
                <span asp-validation-for="NumeroPaginas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroDeLivros/CadastroDeLivros/Views/Livros/Index.cshtml
@model IEnumerable<CadastroDeLivros.Models.Livro>

@{
    ViewData["Title"] = "Index";
}

<h1>Cadastrar Livros</h1>

<p>
    <a asp-action="Create">Cadastrar um novo Livro</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autores)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AnoPublicacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idioma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroPaginas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autores)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnoPublicacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idioma)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroPaginas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LivroID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LivroID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LivroID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CadastroDeLivros/CadastroDeLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroDeLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroDeLivros.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Livros" asp-action="Index">CadastroDeLivros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CadastroDeLivros - <a asp-area="" asp-controller="Livros" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>